ALTER TABLE knowledge_repos
 ADD COLUMN indexed_commit VARCHAR(40) NOT NULL DEFAULT '',
 ADD COLUMN commit_count BIGINT NOT NULL DEFAULT 0,
 ADD COLUMN tag_count BIGINT NOT NULL DEFAULT 0,
 ADD COLUMN branch_count BIGINT NOT NULL DEFAULT 0,
 ADD COLUMN history_complete BOOLEAN NOT NULL DEFAULT FALSE,
 ADD COLUMN source_synced_at DATETIME NULL;
