package callbacks

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
	"sync/atomic"

	einocallbacks "github.com/cloudwego/eino/callbacks"
	"github.com/cloudwego/eino/components"
	einomodel "github.com/cloudwego/eino/components/model"
	einotool "github.com/cloudwego/eino/components/tool"
	"github.com/cloudwego/eino/schema"
)

const draftConfigChangeToolName = "draft_config_change"
const listMetricCatalogToolName = "list_metric_catalog"

const AlertDraftGuardBlockedMessage = "这次没有通过 list_metric_catalog + draft_config_change 生成可应用的 config_draft/draft_hash，我已拦截文字草案，避免把它误当成可确认的告警规则。继续这个创建需求时，我会先查询指标目录，再生成正式草案。"
const alertDraftGuardBlockedMessage = AlertDraftGuardBlockedMessage
const traceServiceRequiredMessage = "这条链路告警还缺少 service。trace_latency / trace_error_rate 必须指定服务名，或只能在当前 traces_spanmetrics_* 只有唯一 service_name 时自动推断。请补充服务名，例如：创建服务 ongrid-manager 的 p95 延迟超过 500ms 持续 10 分钟的告警。"

var collectedSourceMentionRE = regexp.MustCompile(`\b(?:db|custom):[A-Za-z0-9_.:-]+`)
var traceServiceAssignmentRE = regexp.MustCompile(`(?i)\bservice(?:_name)?\s*(?:=|:|：|为|是)\s*["']?([A-Za-z][A-Za-z0-9_.:-]*)["']?`)
var traceChineseServiceAssignmentRE = regexp.MustCompile(`服务\s*(?:=|:|：|为|是)\s*["']?([A-Za-z][A-Za-z0-9_.:-]*)["']?`)
var traceWhitespaceServiceRE = regexp.MustCompile(`(?i)(?:\bservice|服务)\s+["']?([A-Za-z][A-Za-z0-9_.:-]*)["']?`)

type AlertDraftGuardDeps struct {
	UserText string
}

// AlertDraftGuardHandler prevents a model-only "draft" from being
// persisted when the user is creating an alert rule. A real alert-rule
// draft must come from draft_config_change so the payload, preview, and
// draft_hash are generated by backend code rather than free-form text.
type AlertDraftGuardHandler struct {
	userText             string
	draftSucceeded       atomic.Bool
	hideSampleSources    atomic.Bool
	missingMetricMessage atomic.Value
}

func NewAlertDraftGuardHandler(deps AlertDraftGuardDeps) *AlertDraftGuardHandler {
	if !looksLikeAlertRuleCreationRequest(deps.UserText) {
		return nil
	}
	return &AlertDraftGuardHandler{userText: deps.UserText}
}

func (h *AlertDraftGuardHandler) Needed(_ context.Context, info *einocallbacks.RunInfo, timing einocallbacks.CallbackTiming) bool {
	if h == nil || info == nil {
		return false
	}
	switch info.Component {
	case components.ComponentOfChatModel, components.ComponentOfTool:
		return timing == einocallbacks.TimingOnEnd
	default:
		return false
	}
}

func (h *AlertDraftGuardHandler) OnEnd(ctx context.Context, info *einocallbacks.RunInfo, output einocallbacks.CallbackOutput) context.Context {
	if h == nil || info == nil {
		return ctx
	}
	switch info.Component {
	case components.ComponentOfTool:
		tout := einotool.ConvCallbackOutput(output)
		if tout == nil {
			return ctx
		}
		switch info.Name {
		case draftConfigChangeToolName:
			if toolResultLooksLikeConfigDraft(tout.Response) {
				h.draftSucceeded.Store(true)
				if draftResultShouldHideSampleSources(tout.Response) {
					h.hideSampleSources.Store(true)
				}
			}
		case listMetricCatalogToolName:
			if msg := missingMetricMessageFromCatalogResult(tout.Response); msg != "" {
				h.missingMetricMessage.Store(msg)
			}
		}
	case components.ComponentOfChatModel:
		mo := einomodel.ConvCallbackOutput(output)
		if mo == nil || mo.Message == nil {
			return ctx
		}
		if messageCallsTool(mo.Message, draftConfigChangeToolName) {
			return ctx
		}
		mo.Message.Content = h.SanitizeAssistantContent(mo.Message.Content)
	}
	return ctx
}

func (h *AlertDraftGuardHandler) OnStart(ctx context.Context, _ *einocallbacks.RunInfo, _ einocallbacks.CallbackInput) context.Context {
	return ctx
}

func (h *AlertDraftGuardHandler) OnError(ctx context.Context, _ *einocallbacks.RunInfo, _ error) context.Context {
	return ctx
}

func (h *AlertDraftGuardHandler) OnStartWithStreamInput(ctx context.Context, _ *einocallbacks.RunInfo, _ *schema.StreamReader[einocallbacks.CallbackInput]) context.Context {
	return ctx
}

func (h *AlertDraftGuardHandler) OnEndWithStreamOutput(ctx context.Context, _ *einocallbacks.RunInfo, _ *schema.StreamReader[einocallbacks.CallbackOutput]) context.Context {
	return ctx
}

func (h *AlertDraftGuardHandler) SanitizeAssistantContent(content string) string {
	if h == nil {
		return content
	}
	if h.draftSucceeded.Load() {
		if h.hideSampleSources.Load() {
			return sanitizeCollectedSampleSourceMentions(content)
		}
		return content
	}
	if !looksLikeConfirmableAlertDraft(content) {
		return content
	}
	if msg, ok := h.missingMetricMessage.Load().(string); ok && strings.TrimSpace(msg) != "" {
		return msg
	}
	if shouldAskForTraceService(h.userText) {
		return traceServiceRequiredMessage
	}
	return alertDraftGuardBlockedMessage
}

func AlertDraftGuardFromHandlers(handlers []einocallbacks.Handler) *AlertDraftGuardHandler {
	for _, h := range handlers {
		if guard, ok := h.(*AlertDraftGuardHandler); ok {
			return guard
		}
	}
	return nil
}

func LooksLikeAlertRuleCreationText(text string) bool {
	return looksLikeAlertRuleCreationRequest(text)
}

func messageCallsTool(msg *schema.Message, toolName string) bool {
	if msg == nil {
		return false
	}
	for _, tc := range msg.ToolCalls {
		if strings.EqualFold(strings.TrimSpace(tc.Function.Name), toolName) {
			return true
		}
	}
	return false
}

func LooksLikeAlertDraftGuardBlockedMessage(content string) bool {
	lower := strings.ToLower(content)
	return strings.Contains(lower, "draft_config_change") &&
		strings.Contains(lower, "config_draft") &&
		(strings.Contains(content, "拦截文字草案") ||
			strings.Contains(content, "没有通过 draft_config_change") ||
			strings.Contains(content, "我还没有通过 draft_config_change"))
}

func looksLikeAlertRuleCreationRequest(text string) bool {
	lower := strings.ToLower(text)
	if !containsAnyNeedle(text, lower, []string{
		"创建", "新增", "添加", "配置", "生成",
		"create", "add", "configure", "new", "generate",
	}) {
		return false
	}
	return containsAnyNeedle(text, lower, []string{
		"告警", "告警规则", "监控规则", "规则", "链路", "日志",
		"alert", "rule", "monitoring rule", "slo", "burn rate", "metric", "log", "trace",
	})
}

func looksLikeConfirmableAlertDraft(content string) bool {
	lower := strings.ToLower(content)
	if containsAnyNeedle(content, lower, []string{
		"config_draft",
		"apply_config_change",
	}) {
		return true
	}
	hasAlertRule := strings.Contains(content, "告警") ||
		strings.Contains(content, "规则键") ||
		strings.Contains(content, "规则设计") ||
		strings.Contains(strings.ToLower(content), "规则 key") ||
		strings.Contains(lower, "alert") ||
		strings.Contains(lower, "rule_key") ||
		strings.Contains(lower, "draft_hash")
	if !hasAlertRule {
		return false
	}
	confirmableNeedles := []string{
		"草案哈希",
		"确认应用",
		"告警规则草案",
		"draft_hash",
		"sha256:",
		"config_draft",
		"apply_config_change",
	}
	for _, needle := range confirmableNeedles {
		if strings.Contains(lower, needle) || strings.Contains(content, needle) {
			return true
		}
	}
	hasRuleDesign := containsAnyNeedle(content, lower, []string{
		"规则设计",
		"规则 key",
		"规则key",
		"promql",
		"触发条件",
		"生效范围",
	})
	asksForConfirm := containsAnyNeedle(content, lower, []string{
		"需要确认",
		"确认创建",
		"要确认",
		"确认吗",
		"confirm",
		"approve",
	})
	if hasRuleDesign && asksForConfirm {
		return true
	}
	return false
}

func containsAnyNeedle(text, lowerText string, needles []string) bool {
	for _, needle := range needles {
		if strings.Contains(lowerText, needle) || strings.Contains(text, needle) {
			return true
		}
	}
	return false
}

func shouldAskForTraceService(userText string) bool {
	if !looksLikeTraceAlertCreationRequest(userText) {
		return false
	}
	return !requestMentionsTraceService(userText)
}

func looksLikeTraceAlertCreationRequest(text string) bool {
	lower := strings.ToLower(text)
	hasTrace := strings.Contains(text, "链路") ||
		strings.Contains(lower, "trace") ||
		strings.Contains(lower, "span")
	if !hasTrace {
		return false
	}
	return strings.Contains(text, "延迟") ||
		strings.Contains(text, "错误率") ||
		strings.Contains(lower, "latency") ||
		strings.Contains(lower, "error rate") ||
		strings.Contains(lower, "error_rate") ||
		strings.Contains(lower, "p95") ||
		strings.Contains(lower, "p99")
}

func requestMentionsTraceService(text string) bool {
	lower := strings.ToLower(text)
	if strings.Contains(text, "未指定服务") ||
		strings.Contains(text, "没有指定服务") ||
		strings.Contains(text, "缺少服务") ||
		strings.Contains(lower, "without service") ||
		strings.Contains(lower, "missing service") {
		return false
	}
	for _, re := range []*regexp.Regexp{
		traceServiceAssignmentRE,
		traceChineseServiceAssignmentRE,
		traceWhitespaceServiceRE,
	} {
		matches := re.FindStringSubmatch(text)
		if len(matches) != 2 {
			continue
		}
		if isUsableTraceServiceName(matches[1]) {
			return true
		}
	}
	return false
}

func isUsableTraceServiceName(name string) bool {
	value := strings.ToLower(strings.Trim(strings.TrimSpace(name), `"'`))
	if value == "" {
		return false
	}
	switch value {
	case "p50", "p90", "p95", "p99", "latency", "trace", "span", "error", "errors",
		"all", "any", "every", "missing", "unknown", "service":
		return false
	default:
		return true
	}
}

func toolResultLooksLikeConfigDraft(result string) bool {
	var resp struct {
		Kind      string `json:"kind"`
		DraftHash string `json:"draft_hash"`
	}
	if err := json.Unmarshal([]byte(result), &resp); err == nil &&
		strings.TrimSpace(resp.Kind) == "config_draft" &&
		strings.TrimSpace(resp.DraftHash) != "" {
		return true
	}
	lower := strings.ToLower(result)
	return strings.Contains(lower, "config_draft") &&
		strings.Contains(lower, "draft_hash")
}

func draftResultShouldHideSampleSources(result string) bool {
	var resp struct {
		Payload struct {
			Rule struct {
				Kind string                 `json:"kind"`
				Spec map[string]interface{} `json:"spec"`
			} `json:"rule"`
		} `json:"payload"`
	}
	if err := json.Unmarshal([]byte(result), &resp); err != nil {
		return false
	}
	if strings.TrimSpace(resp.Payload.Rule.Kind) != "metric_raw" || resp.Payload.Rule.Spec == nil {
		return false
	}
	if boolish(resp.Payload.Rule.Spec["source_explicit"]) {
		return false
	}
	for _, key := range []string{"expr", "promql", "query", "selector", "label_selector"} {
		if containsExplicitSourceMatcher(resp.Payload.Rule.Spec[key]) {
			return false
		}
	}
	return true
}

func boolish(raw interface{}) bool {
	switch v := raw.(type) {
	case bool:
		return v
	case string:
		switch strings.ToLower(strings.TrimSpace(v)) {
		case "true", "yes", "y", "1", "explicit", "user", "specified", "requested":
			return true
		default:
			return false
		}
	default:
		return false
	}
}

func containsExplicitSourceMatcher(raw interface{}) bool {
	text, ok := raw.(string)
	if !ok {
		return false
	}
	return strings.Contains(text, `ongrid_source="`) ||
		strings.Contains(text, `device_id="`) ||
		strings.Contains(text, `instance="`) ||
		strings.Contains(text, `service="`)
}

func sanitizeCollectedSampleSourceMentions(content string) string {
	return collectedSourceMentionRE.ReplaceAllStringFunc(content, func(match string) string {
		if strings.HasPrefix(match, "custom:") {
			return "某个自定义采集源"
		}
		return "某个数据库采集源"
	})
}

func missingMetricMessageFromCatalogResult(result string) string {
	var resp struct {
		Status      string `json:"status"`
		Query       string `json:"query"`
		Instruction string `json:"instruction"`
	}
	if err := json.Unmarshal([]byte(result), &resp); err != nil {
		return ""
	}
	status := strings.ToLower(strings.TrimSpace(resp.Status))
	if status != "empty" {
		return ""
	}
	query := strings.TrimSpace(resp.Query)
	if query == "" {
		query = "该告警所需指标"
	}
	reason := "当前没有采集到匹配的指标。"
	return fmt.Sprintf("当前指标目录未匹配到 `%s` 所需的已采集指标，因此没有生成可应用的 config_draft，也不会硬造 PromQL 规则。%s 请先配置对应指标采集，或提供精确的指标名/PromQL 后再创建。", query, reason)
}

var _ einocallbacks.Handler = (*AlertDraftGuardHandler)(nil)
var _ einocallbacks.TimingChecker = (*AlertDraftGuardHandler)(nil)
