package apm

import (
	"context"
	"encoding/json"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/ongridio/ongrid/internal/pkg/promquery"
)

func TestReplicaScopeAcrossQueries(t *testing.T) {
	q := testQuery()
	q.InstanceID, q.ServiceVersion = `pod"1`, "1.1.0"
	q.DeviceID, q.ClusterID = `42"`, "7"
	if err := q.Validate(true); err != nil {
		t.Fatal(err)
	}
	for _, source := range []string{"application_metrics", "tempo_spanmetrics"} {
		q.MetricSource = source
		for _, protocol := range []string{"http", "rpc"} {
			q.Protocol = protocol
			expr := q.metricSelector()
			for _, want := range []string{`device_id="42\""`, `cluster_id="7"`, `service_instance_id="pod\"1"`, `service_version="1.1.0"`} {
				if !strings.Contains(expr, want) {
					t.Fatalf("missing %s: %s", want, expr)
				}
			}
			traceQL := TraceQL(q)
			if !strings.Contains(traceQL, `resource.device_id = "42\""`) || !strings.Contains(traceQL, `resource.cluster_id = "7"`) {
				t.Fatal(traceQL)
			}
			if !strings.Contains(traceQL, `resource.service.instance.id = "pod\"1"`) || !strings.Contains(traceQL, `resource.service.version = "1.1.0"`) {
				t.Fatal(traceQL)
			}
		}
	}
	expr := runtimeExpression(q, 5*time.Minute)
	for _, want := range []string{`device_id="42\""`, `cluster_id="7"`, `service_instance_id="pod\"1"`, `service_version="1.1.0"`, `rate(process_cpu_seconds_total`, `rate(jvm_cpu_time_seconds_total`, `last_over_time`, `service_instance_id,instance,service_version`} {
		if !strings.Contains(expr, want) {
			t.Fatalf("missing %s: %s", want, expr)
		}
	}
	q.InstanceID = "bad\ninstance"
	if q.Validate(true) == nil {
		t.Fatal("invalid instance accepted")
	}
}

type runtimeProm struct{}

func (runtimeProm) Query(_ context.Context, expr string, _ time.Time) (*promquery.InstantResult, error) {
	data := `[{"metric":{"service_instance_id":"pod-1","service_version":"1.0"},"value":[1600,"1"]},{"metric":{"service_instance_id":"pod-2","service_version":"1.1"},"value":[1600,"1"]}]`
	if strings.Contains(expr, "apm_runtime") {
		data = `[{"metric":{"apm_runtime":"process_cpu_cores","service_instance_id":"pod-2","service_version":"1.1"},"value":[1600,"0"]}]`
	}
	return &promquery.InstantResult{ResultType: "vector", Result: json.RawMessage(data)}, nil
}
func (runtimeProm) QueryRange(_ context.Context, _ string, _, _ time.Time, _ time.Duration) (*promquery.InstantResult, error) {
	return &promquery.InstantResult{ResultType: "matrix", Result: json.RawMessage(`[{"metric":{"apm_runtime":"process_cpu_cores","service_instance_id":"pod-2","service_version":"1.1"},"values":[[1500,"0.02"],[1600,"0"]]}]`)}, nil
}
func TestRuntimeKeepsVersionAndZeroValues(t *testing.T) {
	q := testQuery()
	q.InstanceID, q.ServiceVersion = "pod-2", "1.1"
	out, err := New(runtimeProm{}, nil, nil).Runtime(t.Context(), q)
	if err != nil {
		t.Fatal(err)
	}
	if len(out.Items) != 1 || len(out.Instances) != 2 {
		t.Fatalf("items/options = %+v", out)
	}
	row := out.Items[0]
	if row.Unit != "cores" || row.Version != "1.1" || row.InstanceID != "pod-2" || row.Value == nil || *row.Value != 0 || len(row.Points) != 2 || *row.Points[0].Value != 0.02 {
		t.Fatalf("runtime = %+v", row)
	}
}

// Read-only acceptance against the persistent six-replica demo. Its failures
// are real HTTP responses generated by the two explicit demo traffic profiles.
func TestAPMReplicaMetricsIntegration(t *testing.T) {
	endpoint := os.Getenv("APM_REPLICAS_PROMETHEUS")
	if endpoint == "" {
		t.Skip("set APM_REPLICAS_PROMETHEUS for the running six-replica demo")
	}
	svc := New(promquery.New(endpoint, nil), nil, nil)
	env, ns := "development", "apm-demo"
	for _, language := range []string{"go", "java", "python"} {
		t.Run(language, func(t *testing.T) {
			q := Query{Start: time.Now().Add(-5 * time.Minute), End: time.Now(), Environment: &env, ServiceNamespace: &ns, ServiceName: "apm-demo-" + language, Protocol: "http"}
			runtime, err := svc.Runtime(t.Context(), q)
			if err != nil {
				t.Fatal(err)
			}
			cpu, memory, jvm := map[string]bool{}, map[string]bool{}, map[string]bool{}
			for _, row := range runtime.Items {
				if row.Value == nil || len(row.Points) < 2 {
					continue
				}
				if row.Name == "process_cpu_cores" && *row.Value >= 0 {
					cpu[row.InstanceID] = true
				}
				if (row.Name == "process_resident_memory_bytes" || row.Name == "process_memory_usage_bytes") && *row.Value > 0 {
					memory[row.InstanceID] = true
				}
				if row.Name == "jvm_heap_memory_used_bytes" && *row.Value > 0 {
					jvm[row.InstanceID] = true
				}
			}
			if len(cpu) != 2 || len(memory) != 2 {
				t.Fatalf("CPU instances=%v memory instances=%v", cpu, memory)
			}
			if language == "java" && len(jvm) != 2 {
				t.Fatalf("JVM memory instances=%v", jvm)
			}
			errors := []float64{}
			for i, version := range []string{"1.0.0", "1.1.0-demo"} {
				q.ServiceVersion = version
				q.InstanceID = "ubuntu-" + language + "-" + []string{"1", "2"}[i]
				overview, err := svc.Overview(t.Context(), q)
				if err != nil || overview.Summary.RPS == nil || *overview.Summary.RPS <= 0 || overview.Summary.ErrorRate == nil {
					t.Fatalf("%s overview=%+v err=%v", version, overview, err)
				}
				errors = append(errors, *overview.Summary.ErrorRate)
				selected, err := svc.Runtime(t.Context(), q)
				if err != nil || len(selected.Items) == 0 {
					t.Fatalf("selected runtime=%+v err=%v", selected, err)
				}
				hasRSS := false
				for _, row := range selected.Items {
					if row.InstanceID != q.InstanceID || row.Version != version {
						t.Fatalf("scope leak: %+v", row)
					}
					if (row.Name == "process_resident_memory_bytes" || row.Name == "process_memory_usage_bytes") && row.Value != nil && *row.Value > 0 && len(row.Points) >= 2 {
						hasRSS = true
					}
				}
				if !hasRSS {
					t.Fatalf("missing scoped RSS for %s", q.InstanceID)
				}
				ops, err := svc.List(t.Context(), q, true)
				if err != nil || len(ops.Items) == 0 {
					t.Fatalf("selected operations=%+v err=%v", ops, err)
				}
			}
			if errors[1]-errors[0] < 8 {
				t.Fatalf("expected distinct demo error profiles: %v", errors)
			}
			t.Logf("two versions/instances have real CPU, memory, scoped operations and errors %.2f%% / %.2f%%", errors[0], errors[1])
		})
	}
}
