{{- if ne .Values.mode "serverless" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ongrid-edge.nodeServiceAccount" . }}
  namespace: {{ include "ongrid-edge.namespace" . }}
  labels:
    {{- include "ongrid-edge.labels" . | nindent 4 }}
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ongrid-edge.controllerServiceAccount" . }}
  namespace: {{ include "ongrid-edge.namespace" . }}
  labels:
    {{- include "ongrid-edge.labels" . | nindent 4 }}
