apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ongrid-edge.nodeServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ongrid-edge.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ongrid-edge.controllerServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ongrid-edge.labels" . | nindent 4 }}
