vi.mock('@/api/devices', () => ({ listDevices: vi.fn().mockResolvedValue({ items: [{ id: 1, name: 'host', environment: 'device-only-env' }], total: 1 }) }));
import { act, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, expect, it, vi } from 'vitest';
import ApmCapturePage from './ApmCapture';
import { getEdge } from '@/api/edges';
import { listEdgePlugins } from '@/api/integrations';
import { getKubernetesCluster } from '@/api/kubernetes';
vi.mock('@/api/edges', () => ({ getEdge: vi.fn() }));
vi.mock('@/api/integrations', () => ({ listEdgePlugins: vi.fn(), setEdgePlugin: vi.fn(), getAutoAPMOptions: vi.fn().mockResolvedValue({ environments: [], namespaces: [] }) }));
vi.mock('@/api/topology', () => ({ listAllNodes: vi.fn().mockResolvedValue([]) }));
vi.mock('@/api/kubernetes', () => ({ getKubernetesCluster: vi.fn(), getKubernetesCapture: vi.fn().mockResolvedValue({ spec: { kubernetes: { rules: [{ namespace: 'shop' }] } }, defaults: {} }), getKubernetesClusterHealth: vi.fn().mockResolvedValue({ namespaces: [] }) }));
vi.mock('@/store/me', () => ({ usePermissions: () => ({ isAdmin: true }) }));
const open = (url: string) => render(<MemoryRouter initialEntries={[url]}><Routes><Route path="/apm/capture/:kind/:id" element={<ApmCapturePage />} /><Route path="/apm" element={<div>Discovery page</div>} /></Routes></MemoryRouter>);
beforeEach(() => {
  vi.clearAllMocks();
  localStorage.setItem('ongrid-locale', 'en-US');
  vi.mocked(getEdge).mockResolvedValue({ id: 67, name: 'Ubuntu', status: 'offline', roles: [], access_key_id: '', last_seen_at: null });
  vi.mocked(listEdgePlugins).mockResolvedValue({ items: [{ plugin_name: 'autoapm', enabled: true, spec: { targets: [{ executable: '/opt/orders', port: 8080, service_name: 'orders' }] } }] });
  vi.mocked(getKubernetesCluster).mockResolvedValue({ id: 48, name: 'prod', mode: 'full-node', status: 'online', created_at: '', updated_at: '' });
});
it('loads a direct host URL as a page and opens only the editor in a dialog', async () => {
  const user = userEvent.setup(); open('/apm/capture/hosts/67');
  expect(await screen.findByRole('heading', { name: 'Configure capture · Ubuntu' })).toBeInTheDocument();
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  await act(async () => { await user.click(screen.getByRole('button', { name: 'Edit orders' })); });
  expect(screen.getAllByRole('dialog')).toHaveLength(1);
  expect(screen.queryByLabelText('Executable path')).not.toBeInTheDocument();
  await user.clear(screen.getByLabelText('Service name'));
  await user.type(screen.getByLabelText('Service name'), 'orders-draft');
  await act(async () => { window.dispatchEvent(new CustomEvent('ongrid-locale-change', { detail: 'zh-CN' })); });
  expect(screen.getByLabelText('服务名称')).toHaveValue('orders-draft');
  expect(getEdge).toHaveBeenCalledTimes(1);
  await act(async () => { window.dispatchEvent(new CustomEvent('ongrid-locale-change', { detail: 'en-US' })); });
  await user.click(screen.getByRole('button', { name: 'Cancel' }));
  await user.click(screen.getByRole('link', { name: 'Back to service discovery' }));
  expect(screen.getByText('Discovery page')).toBeInTheDocument();
});
it('loads a direct Kubernetes URL and returns to the Kubernetes discovery scope', async () => {
  open('/apm/capture/kubernetes/48');
  expect(await screen.findByRole('button', { name: 'Edit shop' })).toBeInTheDocument();
  expect(screen.getByRole('table', { name: 'Configured capture targets' })).toBeInTheDocument();
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  expect(screen.getByRole('link', { name: 'Back to service discovery' })).toHaveAttribute('href', '/apm?tab=discovery&discovery_scope=kubernetes');
});
it('shows a retryable load failure and rejects invalid resource URLs', async () => {
  const user = userEvent.setup();
  vi.mocked(getEdge).mockRejectedValueOnce(new Error('unavailable'));
  const view = open('/apm/capture/hosts/67');
  expect(await screen.findByRole('alert')).toHaveTextContent('unavailable');
  await user.click(screen.getByRole('button', { name: 'Retry' }));
  expect(await screen.findByText('orders')).toBeInTheDocument();
  view.unmount(); vi.clearAllMocks();
  open('/apm/capture/unknown/invalid');
  expect(screen.getByText('Invalid capture configuration URL')).toBeInTheDocument();
  expect(getEdge).not.toHaveBeenCalled();
  expect(getKubernetesCluster).not.toHaveBeenCalled();
});
